# Disable CI
trigger: none

pool:
  vmImage: ubuntu-latest

# Install Node.js
steps:
- task: NodeTool@0
  inputs:
    versionSpec: "18.9.0"
  displayName: "Install Node.js"

# Import Production Environment Variables
- task: Bash@3
  inputs:
    targetType: "inline"
    script: "mv -f .env.production .env"
    workingDirectory: "$(Build.SourcesDirectory)"
  displayName: "Import Production Environment Variables"

# npm install & build
- script: |
    npm install
    npm run build
  displayName: "npm install & build"

# Publish Artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: "$(Build.SourcesDirectory)/build"
    artifact: "build"
    publishLocation: "pipeline"
  displayName: "Publish Artifact"
